# Generated by Django 5.1.6 on 2025-03-03 13:07

from django.db import connection, migrations


def enable_pg_trgm(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_alter_candidate_gender"),
    ]

    operations = [
        migrations.RunPython(enable_pg_trgm),
    ]
