# Generated by Django 5.1.6 on 2025-03-03 13:36

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_auto_20250303_1307"),
    ]

    operations = [
        BtreeGinExtension(),
    ]
